#!/usr/bin/env bash
# Configures Nginx to match web-01 fully, plus a custom X-Served-By header
apt-get -y update
apt-get -y install nginx

echo "Holberton School" > /var/www/html/index.nginx-debian.html

sed -i '/server_name _;/a\\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default

service nginx restart || service nginx start