#!/usr/bin/env bash
# Installs and configures HAProxy to load balance between web-01 and web-02
apt-get -y update
apt-get -y install haproxy

haproxy_config=\
"global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
	timeout connect 5000
	timeout client  50000
	timeout server  50000

frontend http_front
	bind *:80
	default_backend http_back

backend http_back
	balance roundrobin
	server 7168-web-01 13.220.214.222:80 check
	server 7168-web-02 44.203.142.57:80 check
"

echo "$haproxy_config" | tee /etc/haproxy/haproxy.cfg > /dev/null

sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

service haproxy restart